# Generated by Django 5.1.3 on 2024-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Mahasiswa', 'Mahasiswa'), ('Alumni', 'Alumni')], default='', max_length=50),
        ),
    ]
